Fix RevWalk NoSuchMethodError
Currently the plugin does not work on 2.11
While it builds it throws internal server errors
due to the RevWalk.release() method not being in
the new version of jgit.

Change-Id: I2bb91822189f6be5aed3becffbccffbf8704c531