Make sure that `owners` are JDK8 compatible in `stable-3.4`
When `owners` plugin is compiled with JDK8 it fails with the following
errors:

plugins/owners/src/main/java/com/googlesource/gerrit/owners/restapi/GetFilesOwners.java:104: error: cannot find symbol
        projectCache.get(change.getProject()).stream()
                                             ^
  symbol:   method stream()
  location: class Optional<ProjectState>

plugins/owners/src/main/java/com/googlesource/gerrit/owners/restapi/GetFilesOwners.java:129: error: invalid method reference
                      .flatMap(Optional::stream)
                               ^
  cannot find symbol
    symbol:   method stream()
    location: class Optional

It is due to the fact that JDK8 has no Optional.stream function.
Per javadoc, it was added in JDK9.

Replace calls to `Optional.stream` with `map` to make JKD8 compiler
happy.

Change-Id: I318403910edf3d23a3c06dd92bf10e005ca26b70