Update patch set 3
Patch Set 3: Verified-1

This change broke the tests:

2) checkMatchers(com.vmware.gerrit.owners.common.RegexTest)
java.lang.AssertionError: expected:<3> but was:<5>

Patch-set: 3
Reviewer: Luca Milanesio <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1