Update patch set 1
Patch Set 1:

Before this change, bazel build :all would pass for me. After this change, it does not anymore. What am I missing, please? -Getting this error, with this change:

ERROR: (...) owners/owners-autoassign/BUILD:3:1: Executing genrule //owners-autoassign:owners-autoassign failed (Exit 1)

Patch-set: 1
CC: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>