Update patch set 1
Patch Set 1: Code-Review-1

This does not compile under my environment (gerrit stable 2.13) with the following error: 
/home/pakkio/w/GERRIT/gerrit/plugins/gerrit-owners/gerrit-owners/src/main/java/com/vmware/gerrit/owners/OwnersStoredValues.java:45: error: local variable resolver is accessed from within inner class; needs to be declared final
	  return new PathOwners(resolver, db, repository, patchList);
This is the reason why I initially put it as final in my change... Is there another way for dealing with this?

Patch-set: 1
Reviewer: Gerrit User 1023193 <1023193@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1