Fix java.lang.NoClassDefFoundError for commons
Owners common classes need to be explicitly included in the
output fat-jar

Change-Id: I034adec65286eb25e06d64c488eadec83baa5258