Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Before this change, bazel build :all would pass for me. After this change, it does not anymore. What am I missing, please? -Getting this error, with this change:
> 
> ERROR: (...) owners/owners-autoassign/BUILD:3:1: Executing genrule //owners-autoassign:owners-autoassign failed (Exit 1)

Hmm, that also fails for me now.  When I discovered this 'bug' it was when running:

  bazel build owners

which would fail with a similar problem, but because of the 'autoassign' part of the generated name.

Patch-set: 1